# Generated by Django 2.2.1 on 2019-09-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.People')),
            ],
            options={
                'db_table': 'father',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
