# Generated by Django 2.2.1 on 2019-09-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_person_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
